version: '3.7'

services:
  departure-board:
    image: docker.pkg.github.com/benfl3713/departureboard/departure-board:latest
    deploy:
      replicas: 6
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        failure_action: rollback
    expose:
      - "80"

  nginx:
    image: nginx:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        failure_action: rollback
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - departure-board
    ports:
      - "80:4000"
