version: '3.7'

services:
  departure-board:
    image: docker.pkg.github.com/benfl3713/departureboard/departure-board:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        failure_action: rollback
    expose:
      - "80"
    volumes:
      - ./config.xml:/config.xml

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        failure_action: rollback
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - departure-board
    ports:
      - "80:4000"
