version: '3'

services:
  departure-board:
    build:
        context: .
        dockerfile: "./Dockerfile"
        args:
          RTT_Token: "[INSERT_REALTIMETRAINS_TOKEN_HERE]"
    image: departure-board:latest
    ports:
      - "9005:80"