apiVersion: apps/v1
kind: Deployment
metadata:
  name: departure-board
spec:
  replicas: 10
  selector:
    matchLabels:
      app: departure-board
  template:
    metadata:
      labels:
        app: departure-board
    spec:
      containers:
      - name: departure-board
        image: benfl3713/departure-board:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "80m"
          requests:
            memory: "50Mi"
            cpu: "80m"
        ports:
        - containerPort: 80
