name: .NET Core

on: [push]

jobs:
  Build_DepartureBoard:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
    - name: Build Departure Board with dotnet
      run: dotnet build --configuration Release
    - name: Run Departure Board Unit Tests
      run: dotnet test
